dataset_name: 'imagenet1k'
dataset_root_path: '../../data/imagenet1k/ILSVRC/Data/CLS-LOC'
df_train: 'train_1p.csv'
df_trainval: 'train_val_1p.csv'
df_val: 'val_1p.csv'
df_test: 'imagenet1k_test.csv'
folder_train: '.'
folder_val: '.'
folder_test: 'val'
df_classid_classname: 'classid_classname_in1k.csv'