dataset_name: 'imagenet1k'
dataset_root_path: '../../data/imagenet1k/ILSVRC/Data/CLS-LOC'
df_train: 'imagenet1k.csv'
df_trainval: imagenet1k.csv
df_val: 'imagenet1k_test.csv'
df_test: 'imagenet1k_test.csv'
folder_train: 'train'
folder_val: 'val'
folder_test: 'val'
df_classid_classname: 'classid_classname_in1k.csv'
